name: "toy"
data {
  name: "train_data"
  file_pattern: "/storage/data1/dbm/deepnet/deepnet/examples/toy/sim3.train.npy"
  size: 5000
  dimensions: 100
  num_labels : 20
  sparse: true
}
data {
  name: "validation_data"
  file_pattern: "/storage/data1/dbm/deepnet/deepnet/examples/toy/sim3.valid.npy"
  size: 1000
  dimensions: 100
  num_labels : 20
  sparse: true
}
data {
  name: "test_data"
  file_pattern: "/storage/data1/dbm/deepnet/deepnet/examples/toy/sim3.test.npy"
  size: 1000
  dimensions: 100
  num_labels : 20
  sparse: true
}
gpu_memory: "5G"
main_memory: "32G"
