optimizer: CD
stopcondition {
  all_processed: false
  steps: 100000
}
train: true
batchsize: 100
data_proto: "/storage/data1/dbm/deepnet/deepnet/examples/mnist/mnist.pbtxt"
eval_after: 1000
checkpoint_after: 100000
checkpoint_directory: "/storage/data1/dbm/deepnet/deepnet/examples/checkpoints"
randomize: true
show_after: 1000
